### ISSUE TITLE
Can't configure custom registry script in nuxt.config.ts (myCustomScript is not defined)

### ISSUE THREAD

**Issue by bernhardberger** [nuxt/scripts#270]
### 🐛 The bug

```bash
myCustomScript is not defined

at eval (./virtual:nuxt:/home/projects/nuxt-starter-pkwfkx/.nuxt/plugins/server.mjs#cjs:40:89)
at Module.executeAsync (./node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs:130:19)
at setup (./virtual:nuxt:/home/projects/nuxt-starter-pkwfkx/.nuxt/plugins/server.mjs#cjs:40:65)
at eval (./node_modules/.pnpm/nuxt@3.13.1_vite@5.4.5/node_modules/nuxt/dist/app/nuxt.js#cjs:141:60)
at fn (./node_modules/.pnpm/nuxt@3.13.1_vite@5.4.5/node_modules/nuxt/dist/app/nuxt.js#cjs:223:44)
at Object.callAsync (./node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs:87:55)
at eval (./node_modules/.pnpm/nuxt@3.13.1_vite@5.4.5/node_modules/nuxt/dist/app/nuxt.js#cjs:226:56)
at Object.runWithContext (./node_modules/.pnpm/@vue+runtime-core@3.5.5/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js#cjs:3903:18)
at callWithNuxt (./node_modules/.pnpm/nuxt@3.13.1_vite@5.4.5/node_modules/nuxt/dist/app/nuxt.js#cjs:226:24)
```

```typescript

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  modules: [
    '@nuxt/scripts',
    './modules/my-custom-registry-script-module/src/module.ts',
  ],

  scripts: {
    registry: {
      myCustomScript: {
        src: 'https://example.com/some-bogus-source.js',
      },
    },
  },

  compatibilityDate: '2024-08-21',
});
```

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-starter-yxpzcr?file=nuxt.config.ts

### 🌈 Expected behavior

I have extended the Script Registry through the `scripts:registry` hook in a custom module. I expect it to be configurable in `nuxt.config.ts ` via `scripts.registry.myCustomModule` key (see linked reproduction).

**Comment by bernhardberger** [comment]
I was led to believe that the `scripts:registry` was an object by the docs: https://scripts.nuxt.com/docs/api/nuxt-hooks

However, in reality, it's just an array.

this works:
```
nuxt.hooks.hook('scripts:registry', async (registry) => {
      registry.push({
        // used in DevTools
        label: 'OneTrust SDK',
        logo: ``,
        src: false,
        category: 'consent-management',
        import: onetrustRegistry.import,
      })
    })
    ```
A lot of confusion created by: #267
