### ISSUE TITLE
Error installing package

### ISSUE THREAD

**Issue by hognevevle** [nuxt/scripts#283]
### 🐛 The bug

Trying to install per the [docs](https://scripts.nuxt.com/docs/getting-started/installation): 
```
npx nuxi@latest module add @nuxt/scripts

 ERROR  [GET] "https://npm.pkg.github.com//@nuxt/scripts/latest": 405 Method Not Allowed                                                                              9:02:27 PM

  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async $fetch2 (/Users/hognevevle/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.b88e7b0f.mjs:340:15)
  at async resolveModule (/Users/hognevevle/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/chunks/add2.mjs:262:15)
  at async Object.setup (/Users/hognevevle/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/chunks/add2.mjs:136:15)
  at async runCommand$1 (/Users/hognevevle/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.3e201632.mjs:1620:5)
  at async runCommand$1 (/Users/hognevevle/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.3e201632.mjs:1639:11)
  at async runCommand$1 (/Users/hognevevle/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.3e201632.mjs:1639:11)
  at async runMain$1 (/Users/hognevevle/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.3e201632.mjs:1777:7) 



 ERROR  [GET] "https://npm.pkg.github.com//@nuxt/scripts/latest": 405 Method Not Allowed                                                                              9:02:27 PM

```

### 🛠️ To reproduce

npx nuxi@latest module add @nuxt/scripts

### 🌈 Expected behavior

Installation to succed.

### ℹ️ Additional context

This works: 
`npx nuxi module add @nuxt/scripts`

**Comment by harlan-zw** [comment]
This seems to be an upstream issue with [Nuxt CLI](https://github.com/nuxt/cli) or NPM itself, unfortunately, there's nothing I can do on my end.

For reference this command works fine on my computer.
